# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiferayIssuesCli < Formula
  desc "CLI tool for managing Liferay Jira tickets"
  homepage "https://github.com/david-truong/liferay-issues-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.1.0/issues_0.1.0_darwin_amd64.tar.gz"
      sha256 "7775ddff8bda88a230481638749960c81e5fdb36220da8991c7be330c806dd69"

      define_method(:install) do
        bin.install "issues"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.1.0/issues_0.1.0_darwin_arm64.tar.gz"
      sha256 "2e99c9f355fdb8aedbe8e159c27e364624edebcb4bc282714d31a44051158bb0"

      define_method(:install) do
        bin.install "issues"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.1.0/issues_0.1.0_linux_amd64.tar.gz"
      sha256 "7a2f63ae22f32fae1f32fa316e2ac4b415babba1527b2cb55c3321f17af6248e"
      define_method(:install) do
        bin.install "issues"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.1.0/issues_0.1.0_linux_arm64.tar.gz"
      sha256 "2dad8e3434543f090475d63ccb3f7476ff6e840f706c5e18d760b56695df5565"
      define_method(:install) do
        bin.install "issues"
      end
    end
  end

  test do
    system "#{bin}/issues", "--version"
  end
end
