# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LiferayIssuesCli < Formula
  desc "CLI tool for managing Liferay Jira tickets"
  homepage "https://github.com/david-truong/liferay-issues-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.3.0/issues_0.3.0_darwin_amd64.tar.gz"
      sha256 "80ae2a875441af950e6f85b4d7de221e08d57be2726c7bcc199ee570ef8fc255"

      define_method(:install) do
        bin.install "issues"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.3.0/issues_0.3.0_darwin_arm64.tar.gz"
      sha256 "b350f4549654230f7194490b713ed0774e83b21235753f2102347c3bb13a34ed"

      define_method(:install) do
        bin.install "issues"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.3.0/issues_0.3.0_linux_amd64.tar.gz"
      sha256 "b87a07eb2f840851541e768fd9e6e28202bf412183a635dccfd259b7a19294f3"
      define_method(:install) do
        bin.install "issues"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-issues-cli/releases/download/v0.3.0/issues_0.3.0_linux_arm64.tar.gz"
      sha256 "f2de9c1a00bb21b1b8c68de343d65b8864621715f885be613420a5867b86c3b9"
      define_method(:install) do
        bin.install "issues"
      end
    end
  end

  test do
    system "#{bin}/issues", "--version"
  end
end
