# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liferay < Formula
  desc "CLI for Liferay portal development workflows (build modules, manage worktrees, run containers)"
  homepage "https://github.com/david-truong/liferay-portal-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_darwin_amd64.tar.gz"
      sha256 "8df90ead7b4592e8710b7c381a40d5cf54b740ae68f7789132996a83919eedf3"

      define_method(:install) do
        bin.install "liferay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_darwin_arm64.tar.gz"
      sha256 "e594fbb60a703345cb937fa660daa74acbae00764d8874cce4d43d79e7d6102b"

      define_method(:install) do
        bin.install "liferay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_linux_amd64.tar.gz"
      sha256 "73cdee1b9599b78d9a7b1fa1b1e10de30aa72ae0a070aa4d891d92ba7a3a7c53"
      define_method(:install) do
        bin.install "liferay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_linux_arm64.tar.gz"
      sha256 "fb650e9a2578dd536219d244dbb84acd08176e98609814ac28dad5766e552fee"
      define_method(:install) do
        bin.install "liferay"
      end
    end
  end

  test do
    system "#{bin}/liferay", "--version"
  end
end
