# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Liferay < Formula
  desc "CLI for Liferay portal development workflows (build modules, manage worktrees, run containers)"
  homepage "https://github.com/david-truong/liferay-portal-cli"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_darwin_amd64.tar.gz"
      sha256 "dac58599322d5755c9b39ae9c689b618eaeff8452b55e6ec3a949e8d10bbfdd7"

      define_method(:install) do
        bin.install "liferay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_darwin_arm64.tar.gz"
      sha256 "0eb3bcc850a13e61741c32061c7c3b8752d07392fc0536d4d7e7118ad5581760"

      define_method(:install) do
        bin.install "liferay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_linux_amd64.tar.gz"
      sha256 "e4b2b86f97ba01f17a3a0a4abbbc9d38fc3b84b958a52e4d3b0471ffa4e4f044"
      define_method(:install) do
        bin.install "liferay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/david-truong/liferay-portal-cli/releases/download/v1.2.0/liferay_1.2.0_linux_arm64.tar.gz"
      sha256 "6f452d19d6af715ad9c3bcf995c768e133c5c8eedc330426004f25ef097ba427"
      define_method(:install) do
        bin.install "liferay"
      end
    end
  end

  test do
    system "#{bin}/liferay", "--version"
  end
end
